---
- hosts: all
  vars:
    root_db_password: 
  gather_facts: True
  tasks:
    - name: Update the OS
      dnf: name=* state=latest

    - name: Install MySQL/MariaDB
      dnf: name=mysql-server state=installed

    # Required for Ansible to configure MySQL
    - name: Install MySQL-python
      dnf: name=MySQL-python state=installed

    - name: Install MySQL-dev
      dnf: name=mysql-devel state=installed

    - name: Install git
      dnf: name=git state=installed

    - name: vim
      dnf: name=vim-enhanced state=installed

    - name: Install system ruby
      dnf: name=ruby state=installed

    - name: Setup keys for RVM
      sudo: no
      shell: "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"

    - name: Install RVM with Ruby 2.1.7
      sudo: no
      shell: "curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1.7"

    - name: Set default RVM Ruby
      sudo: no
      shell: rvm alias create default ruby-2.1.7

    - name: Ensure MySQL/MariaDB is running
      command: systemctl start mariadb

    - name: Ensure MySQL/MariaDB starts at boot
      command: systemctl enable mariadb.service

    - name: Ensure IPTables is not running
      command: systemctl disable firewalld
      command: systemctl stop firewalld

    - name: Copy the my.cnf
      template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: Update MySQL Root Password
      mysql_user: name=root host=$item password=$root_db_password
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1
        - localhost

    - name: Annonymous Users not in MySQL
      mysql_user: name='' host=$item state=absent
      with_items:
        - localhost
        - $inventory_hostname

    - name: Test Database is Removed
      mysql_db: name=test state=absent

    - file: dest=/vagrant/repos owner=vagrant group=vagrant state=directory
